services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: |
      apt-get update && apt-get install -y \
        ffmpeg \
        wget \
        ca-certificates \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libdbus-1-3 \
        libgdk-pixbuf2.0-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        xdg-utils \
        --no-install-recommends

      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
      chmod +x /usr/local/bin/yt-dlp
      npm install
    startCommand: node index.js
    envVars:
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome"
    plan: free
