services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: |
      apt-get install -y \
      ffmpeg \
      libnss3 \
      libatk1.0-0 \
      libatk-bridge2.0-0 \
      libcups2 \
      libdrm2 \
      libxcomposite1 \
      libxdamage1 \
      libxrandr2 \
      libasound2 \
      libxshmfence1 \
      libgbm1 \
      libx11-xcb1 \
      libx11-6 \
      libnss3 \
      libxss1 \
      libgtk-3-0 \
      xdg-utils \
      wget \
      curl \
      ca-certificates \
      fonts-liberation \
      --no-install-recommends


      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
      chmod +x /usr/local/bin/yt-dlp
      npm install
    startCommand: node index.js
    envVars:
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome"
    plan: free
